sonar.projectKey=tadanobutubutu_flowscout
sonar.organization=tadanobutubutu
sonar.host.url=https://sonarcloud.io

sonar.sources=lib
sonar.tests=test
sonar.dart.lcov.reportPath=coverage/lcov.info
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,lib/src/localization/**
