version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.10
    working_directory: ~/repo

jobs:
  build-android:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Clone Flutter SDK
          command: |
            git clone https://github.com/flutter/flutter.git -b stable --depth 1
            echo 'export PATH="$PATH:$(pwd)/flutter/bin"' >> $BASH_ENV
      - run:
          name: Flutter Doctor
          command: flutter doctor
      - run:
          name: Build Release APK
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-android:
          filters:
            branches:
              only:
                - main
                - dev
